services:
  
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
        - spooq   
      
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
        - spooq    
  
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
        - spooq    

  spark-worker-3:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
        - spooq
  
  spark-history-server:
      image: bde2020/spark-history-server:3.3.0-hadoop3.3
      container_name: spark-history-server
      depends_on:
        - spark-master
      ports:
        - "18081:18081"
      volumes:
        - /tmp/spark-events-local:/tmp/spark-events
      networks:
        - spooq  

  spooq:
    image: bde2020/spark-base:3.3.0-hadoop3.3
    container_name: spooq1
    ports:
      - 4040:4040
      - 10001:10001
      - 4242:4242
    environment:
      - SPOOQ_HOME=/spooq
      - SPOOQ_PACKAGES=org.mongodb.spark:mongo-spark-connector:10.0.4
    volumes:
      - ./data:/data
      - ./spooq:/spooq
      - ./conf:/conf
    command: >
      /spooq/bin/spooq -r -c /conf/hello.conf --http
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
      - spark-worker-3
    networks:
      - spooq

networks:
  spooq:
